name: Deploy discord discord_telegram_site_check_bot
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: docker build -t site_checker .
      - run: docker-compose up -d