name: Deploy discord_bot discord_bot
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t site_checker .
      - run: docker-compose run -e TG_TOKEN=${{ secrets.TG_TOKEN }} -e DIS_TOKEN=${{ secrets.DIS_TOKEN }} web python console.py
      - run: docker-compose up -d

